# Port c?a ?ng d?ng (m?c ??nh là 8080)
server.port=8080

# C?u hình OpenWeatherMap API
openweathermap.api.url=https://api.openweathermap.org/data/2.5/weather
# Thay YOUR_API_KEY_HERE b?ng key th?t c?a b?n
openweathermap.api.key=5b87497e897d6fd95e659920445a8546